name: Build and Push React App

on:
  push:
    branches:
      - main  # Trigger only on main branch changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Upgrade to Node.js 20

      - name: Install dependencies
        run: npm install --force  # Use --force only if necessary

      - name: Build the React app
        run: npm run build  # This should now work properly

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t digitalizr/enmsgo_landing_page:0.1 .

      - name: Push Docker image
        run: |
          docker push digitalizr/enmsgo_landing_page:0.1


          # **Trigger webhook after the image is pushed**
      - name: Notify EC2 to Deploy
        run: |
          curl -X POST http://ec2-52-221-226-242.ap-southeast-1.compute.amazonaws.com:8050/webhook -H "Content-Type: application/json" -d '{"trigger": "docker_push"}'