name: Build and Push React App

on:
  push:
    branches:
      - main  # Trigger only on main branch changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Upgrade to Node.js 20

      - name: Install dependencies
        run: npm install --force  # Use --force only if necessary

      - name: Build the React app
        run: npm run build  # This should now work properly

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t digitalizr/enmsgo_landing_page:0.1 .

      - name: Push Docker image
        run: |
          docker push digitalizr/enmsgo_landing_page:0.1

      # New step: Set up SSH for EC2 deployment
      - name: Set up SSH for EC2 deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}



      - name: SSH into EC2 and deploy Docker image
        run: |
            ssh -t -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
              echo "Starting docker pull..."
              /usr/bin/docker pull digitalizr/enmsgo_landing_page:0.1 && echo "Image pulled successfully" || echo "Image pull failed"
              echo "Stopping existing container (if any)..."
              /usr/bin/docker stop enmsgo_landing_page_container || true
              echo "Removing existing container (if any)..."
              /usr/bin/docker rm enmsgo_landing_page_container || true
              echo "Starting new container..."
              /usr/bin/docker run -d -p 8080:80 --name enmsgo_landing_page_container digitalizr/enmsgo_landing_page:0.1
              echo "Listing all containers..."
              /usr/bin/docker ps -a
            EOF
        